CREATE TABLE [dbo].[Answers]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [GameId] UNIQUEIDENTIFIER NOT NULL, 
    [SongId] UNIQUEIDENTIFIER NOT NULL, 
    [Points] FLOAT NOT NULL, 
    [PlayerId] UNIQUEIDENTIFIER NOT NULL
)
