CREATE TABLE [dbo].[Players]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Name] NVARCHAR(25) NOT NULL, 
    [GameId] UNIQUEIDENTIFIER NOT NULL, 
    [Points] FLOAT NOT NULL, 
    [Rounds] INT NOT NULL DEFAULT 0, 
    [UserId] UNIQUEIDENTIFIER NULL
)
